{"name": "test_another", "status": "skipped", "statusDetails": {"message": "Skipped: [ISSUE-23414] Issue with network connection", "trace": "('C:\\\\Users\\\\mrnot\\\\PycharmProjects\\\\pythonProject\\\\tests\\\\users\\\\test_users.py', 10, 'Skipped: [ISSUE-23414] Issue with network connection')"}, "start": 1709819119126, "stop": 1709819119126, "uuid": "9066fa4c-dd85-40ec-90fd-500b27af6168", "historyId": "19630dc244333b530cc14c893795ee5f", "testCaseId": "19630dc244333b530cc14c893795ee5f", "fullName": "tests.users.test_users#test_another", "labels": [{"name": "tag", "value": "@pytest.mark.skip('[ISSUE-23414] Issue with network connection')"}, {"name": "tag", "value": "production"}, {"name": "tag", "value": "staging"}, {"name": "parentSuite", "value": "tests.users"}, {"name": "suite", "value": "test_users"}, {"name": "host", "value": "DESKTOP-8NHQB09"}, {"name": "thread", "value": "2872-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.users.test_users"}]}